title: "HashtagMarky"
url: "https://hashtagmarky.com"
baseurl: ""
author: HashtagMarky
description: >
  Pokémon ROM Hacker, Book Lover & Tech Builder. Follow the development of Pokémon Ikigai,
  a custom GBA ROM hack, plus sci-fi and fantasy book reviews with some tech builds in between.

colors:
  orange: "#F09040"
  yellow: "#F8D840"
  green:  "#5CB85C"
  red:    "#EA594d"
  blue:   "#5B9BD5"

github_username: HashtagMarky
# twitter_username: hashtagmrky
instagram_username: hashtagmarky
# youtube_channel: hashtag-marky
# tiktok_username: HashtagMarky
discord_invite: eMMUGXfpkd

collections:
  devlog:
    output: true
    permalink: /devlog/:name/
  books:
    output: true
    permalink: /books/:name/
  versions:
    output: false

defaults:
  - scope:
      path: "_devlog"
      type: devlog
    values:
      layout: devlog
      og_type: article
  - scope:
      path: "_books"
      type: books
    values:
      layout: book
      og_type: article

feed:
  collections:
    - devlog
    - books

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.DS_Store"
  - "**/DRAFT*.md"
  - productions/ikigai/ikigai.md
  - productions/ikigai/credits.md
